#!/bin/sh
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run fu
speed=1
sh="square"

p1="-4  -3" 
p2="2   -3" 
p3="-3  3"
p4="3   3"

x_0=1
y_0=0
x_15=0.788675134594813 
y_15=0.211324865405187 
x_30=0.633974596215561 
y_30=0.366025403784439 
x_45=0.5              
y_45=0.5               
x_60=0.366025403784439 
y_60=0.633974596215561 
x_75=0.211324865405187 
y_75=0.788675134594813 
x_90=0 
y_90=1                 

echo "start"
for i in {0..90..15}
    do
        var_x="x_${i}"
        var_y="y_${i}"
        
        if [ -d $i ];then # delete files
            rm -r $i
        fi
        mkdir $i
        # copy essential files
        cp -r $sh/{0,postProcessing,constant,Allrun,foam.foam,system}  $i/
        # change angle of waterflow
        sed -i "19s/.*/internalField   uniform (${!var_x} ${!var_y} 0);/"   $i"/0/U"
        
        # change the size of square
        sed -i "24s/.*/($p1  0)    /"  $i"/constant/polyMesh/blockMeshDict"
        sed -i "25s/.*/($p2  0)    /"  $i"/constant/polyMesh/blockMeshDict"
        sed -i "26s/.*/($p3  0)    /"  $i"/constant/polyMesh/blockMeshDict"
        sed -i "27s/.*/($p4  0)    /"  $i"/constant/polyMesh/blockMeshDict"
                        
        sed -i "36s/.*/($p1  1)    /"  $i"/constant/polyMesh/blockMeshDict"
        sed -i "37s/.*/($p2  1)    /"  $i"/constant/polyMesh/blockMeshDict"
        sed -i "38s/.*/($p3  1)    /"  $i"/constant/polyMesh/blockMeshDict"
        sed -i "39s/.*/($p4  1)    /"  $i"/constant/polyMesh/blockMeshDict"
        # go through each folder run application
        cd $i
        rm -r [1-9]*
        rm -r processor[0-7]
        echo "clean done!"
        runApplication blockMesh
        echo "blockMesh done!"
        runApplication decomposePar
        echo "decompose done!"
        runApplication mpirun -np 8 pisoFoam -parallel
        echo "mpi done!"
        runApplication reconstructPar
        echo "reconstruct done!"
        rm -r processor[0-7]
        echo "delete temp files"
        cd ..
    done
