#!/bin/sh
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run fu
rm -r [1-9]*
rm -r processor[0-7]
runApplication blockMesh
runApplication decomposePar
runApplication mpirun -np 8 pisoFoam -parallel
runApplication reconstructPar
#------------------------------------------------------------------------------
